BEGIN
   WAITFOR TIME '18:04'
   MERGE INTO V6TABLEDES DEST
USING (SELECT TOP 100 * FROM V6TABLEDES ORDER BY MYBIGINT DESC) SRC 
ON (DEST.MYBIGINT=SRC.MYBIGINT)
WHEN MATCHED THEN 
UPDATE  SET MYVARCHAR=SRC.MYVARCHAR
WHEN NOT MATCHED THEN 
INSERT  VALUES(SRC.MYBIGINT,SRC.MYVARCHAR);

END
