DECLARE

FUNCTION callMe(p_val in VARCHAR2) RETURN NUMBER IS
  LocalVar VARCHAR2(100);
BEGIN
  LocalVar := 'HAI';
  RETURN 1;
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;
END callMe;

BEGIN DBMS_OUTPUT.PUT_LINE(callMe('HELLO')); END;
